name: cabo_counter
version: 1.0.6+1032
publish_to: none

environment:
  sdk: ^3.5.4
description: Mobile app for the card game Cabo

dependencies:
  collection: ^1.18.0
  confetti: ^0.6.0
  cupertino_icons: ^1.0.8
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  file_picker: ^10.1.2
  file_saver: ^0.2.6
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_vibrate:
    # Temporary fix included until the package is updated on pub.dev
    git:
      url: https://github.com/dev-mahmoud-elshenawy/flutter_vibrate-xcode16.3-fix
      ref: master
  flutter_whatsnew: ^1.0.5+2
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.3.0
  intl: any
  json_schema: ^5.2.1
  once: ^1.7.1
  package_info_plus: any
  path_provider: ^2.1.1
  provider: ^6.1.5+1
  # Temporary fix since the flutter fix is on stable channel
  # https://github.com/notDmDrl/pull_down_button/issues/74#issuecomment-3387231862
  pull_down_button:
    git:
      url: https://github.com/TimeFinderApp/pull_down_button
      ref: d7c9ffbc5b1617b385635a0f99b31ae35d13740b
  rate_my_app: ^2.3.2
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^30.1.37
  url_launcher: any
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_oss_licenses: ^2.0.1
  test: ^1.25.15

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/cabo_counter-logo_rounded.png
    - assets/game_list-schema.json
    - assets/game-schema.json
