name: Push Pipeline

on:
  push:
    branches:
      - "development"
      - "main"

permissions:
  contents: write

jobs:
  version:
    name: "Bump version number"
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Bump version
        uses: stikkyapp/update-pubspec-version@v2
        with:
          strategy: 'patch'
          bump-build: true
          path: './pubspec.yaml'

      - name: Commit version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git pull --rebase --autostash
          git commit -m "Updated version number [skip ci]"
          git push origin HEAD:${{ github.ref_name }}

  licenses:
    name: "Generate OSS Licenses"
    runs-on: ubuntu-latest
    needs: version
    if: ${{ always() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Generate oss_licenses.dart
        run: flutter pub run dart_pubspec_licenses:generate --output lib/presentation/views/about/licenses/oss_licenses.dart

      - name: Check for changes
        id: check_changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit Changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase --autostash
          git add .
          git commit -m "Updated licenses [skip ci]"
          git push origin HEAD:${{ github.ref_name }}

  localizations:
    name: "Update localizations"
    runs-on: ubuntu-latest
    needs: licenses
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Remove unused localization keys
        run: dart run remove_unused_localizations

      - name: Sort .arb-Files
        run: |
          shopt -s nullglob
          for file in lib/l10n/arb/app_*.arb; do
            echo "Sorting $file"
            dart run arb_utils sort "$file"
          done

      - name: Generate localizations
        run: flutter gen-l10n --no-use-deferred-loading

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain lib/l10n)" ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit generated localizations
        if: steps.check_changes.outputs.has_changes == 'true'
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git fetch origin "$BRANCH_NAME"
          git checkout "$BRANCH_NAME"

          if [ -n "$(git status --porcelain lib/l10n)" ]; then
             git config --global user.name "GitHub Actions"
              git config --global user.email "actions@github.com"
              git pull --rebase --autostash
              git add .
              git commit -m "Updated localizations [skip ci]"
              git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi

  format:
    name: "Format code"
    runs-on: ubuntu-latest
    needs: localizations
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Sort pubspec.yaml
        run: dart run sort_pubspec_dependencies

      - name: Check code format
        id: check_format
        continue-on-error: true
        run: flutter analyze lib test

      - name: Format code
        if: steps.check_format.outcome == 'failure'
        run: |
          dart fix --apply lib
          dart fix --apply test

      - name: Commit changes
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git fetch origin "$BRANCH_NAME"
          git checkout "$BRANCH_NAME"
          
          if [ -n "$(git status --porcelain lib test pubspec.yaml)" ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add lib test pubspec.yaml
            git commit -m "Formatted code [skip ci]"
            git pull --rebase --autostash origin "$BRANCH_NAME"
            git push origin HEAD:$BRANCH_NAME
          else
            echo "No changes to commit"
          fi

      - name: Verify format
        run: flutter analyze lib test

  test:
    runs-on: ubuntu-latest
    name: "Testing code"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

  build:
    name: "Building for Android"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
