name: Push Pipeline

on:
  push:
    branches:
     - "develop"
     - "main"

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          persist-credentials: true

      - name: Bump version
        uses: stikkyapp/update-pubspec-version@v2
        with:
          strategy: 'patch'
          bump-build: true
          path: './pubspec.yaml'

      - name: Commit version bump
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Actions: Updating version [skip ci]"
          git push origin HEAD:${{ github.ref_name }}

  generate_licenses:
    runs-on: ubuntu-latest
    needs: bump_version
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref_name }}
        fetch-depth: 0
        persist-credentials: true

    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.38.6

    - name: Get dependencies
      run: flutter pub get

    - name: Generate oss_licenses.dart
      run: flutter pub run dart_pubspec_licenses:generate --output lib/presentation/views/about/licenses/oss_licenses.dart

    - name: Check for changes
      id: check_changes
      run: |
        if [[ $(git status --porcelain) ]]; then
          echo "changes_detected=true" >> $GITHUB_OUTPUT
        else
          echo "changes_detected=false" >> $GITHUB_OUTPUT
        fi
            
    - name: Commit Changes
      if: steps.check_changes.outputs.changes_detected == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Actions: Licenses updated [skip ci]"
        git push origin HEAD:${{ github.ref_name }}

  sort_arb_files:
    runs-on: ubuntu-latest
    needs: generate_licenses
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Sort ARB files
        run: flutter pub run intl_utils:sort

      - name: Check for changes
        id: check_changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit Changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "

  lint:
    runs-on: ubuntu-latest
    needs: sort_arb_files
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Check Formatting
        run: flutter analyze

  format:
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ failure() && needs.lint.result == 'failure'}} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get & upgrade dependencies
        run: |
          flutter pub get
          flutter pub upgrade --major-versions
          
      - name: Auto-format
        run: |
          dart format .
          dart fix --apply

      - name: Check for changes
        id: check_changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi
            
      - name: Commit Changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Actions: Auto-formatting [skip ci]"
          git push

  test:
    needs: generate_licenses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get
          
      - name: Run Tests
        run: flutter test

  build:
    runs-on: ubuntu-latest
    needs: generate_licenses
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.38.6

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
